language: node_js
node_js:
  - node

env:
  global:
    - NODE_VERSION=stable

git:
  depth: 3

branches:
  only:
  - master

cache:
  yarn: true

before_install:
  - set -e

install:
  - npm i -g yarn
  - yarn install

script:
  - yarn run build
  - yarn run test
  - node ./scripts/release.js

after_script:
  - echo "BUILD FINISHED"
