language: node_js
node_js:
  - node

env:
  global:
    - NODE_VERSION=stable

git:
  depth: 3

branches:
  only:
  - master

cache:
  yarn: true

before_install:
  - set -e
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install

script:
  - yarn run build
  - yarn run test
  - yarn run release

after_script:
  - echo "BUILD FINISHED"

notifications:
  email: false
  slack:
    secure: gDLtiwIIM64V7N2YjgT8TF6o3uHHYgBPmykXSg4Ht2wp0cNR3zCZg8kdAJWuBKvbAxjE04pGez0C54mDor+7gz8Rl7gkdhGFxdpgPoy5ARDdx8upUqIcxAVn9n7ncmUTmY9vXqNGz69Au81ORSLei3sk9YyP/uyzvExphsaBM1vjg/71sWVq9elJeFKv03MGK7SG1rRXSqb4qDHlDeOOSB540WcJBZy3o3P3b8mWaY1qPIArSeQkPGu/dKVtrY7rnSSBkUNlNV5nVbKor7uVe+l5I1ojPpMbvLHnnBvcEmt9DQAJLPWd9sGZ9R18BjcCKVJxTShTu/0xDvUyFi9U2WwUmpomTyoHhnmnF6N6s2JuHs0qHSU5Ja45RALl5trOq8qUL/qAR4koxKRenpCPP/TrvzH4qsqEp/811gKUSSvZeAK+K5GrJqWqTUqD/DWRTf4vyWIvhgJjED3An6dIdjP5wD+7bAZVHHL+67teLkSV0jKXAoQHzIdZKobRIlufuaZqoSVZDFWVAAuqJz4HykiNHxzmjqtCwtshcEFWZPG4wFgNpNdpq8HxQ+uKMiDP99+2s5Eaoh37UgJoDwlPBlvSdACEKZ9PxrV0sMeKW6vkZPfEfskh4mlIqUnf0iD3X7Nl/XslL5BHRcO4dNWsKSjYuQ0mCm3JpW0L/dZPnl4=
