language: node_js
node_js:
  - node

env:
  global:
    - NODE_VERSION=stable

git:
  depth: 3

branches:
  only:
  - master

cache:
  yarn: true
  directories:
    - $HOME/.yarn-cache

before_install:
  - set -e

install:
  - npm i -g yarn
  - yarn

script:
  - yarn run build
  - yarn run test

after_script:
  - echo "BUILD FINISHED"

#deploy:
#  api_key:
#    secure: twGPUL2ruFhcm8H80iJWWqllBeMSUUPkjjfD0kWMbs09iBsja+JSTZH9t90g9I3+GVYz3v8JOOIEnc1n7FBm9M4Kxtf9qWrNwtha5K6jQ38N6OtrRs2ZtMlU6SPLH/Stz5wPLCeyunEv7A6InjtSThYpuEqUDtzRAchflBW/1OaZIAreX6kpP+pTQhEaJ1vo4Lnwu42h/fQeIi2O70Yrv+3aK+n3zpOrgjuYcitF6Fhd+JhucUUd5DhpgF4/Gs1Pb87Mumesw8qhPq2I24GPVjMBX1V/kVvzhYAi9U1Ae7MNMdzHedIQp9hjAflWloF4KYrbX4Xbn2PZlJ6Pati4vz3u6qZ0VBChhNTTGPdIg0sCjd+eFv2UHEqrAVLA/9zF50G7BXeaeJBNQ9w3W/a27HZEhIjFZn+lDXEiLnLzkEAiiylVOhMRHV0QTSU+jGvCH2HnBsCWtl4cSde7XNC3xxLXUUfdzc0pxKp8VVr2kk8ZXrJqllF8xGl8PUNGiF+aWNgYcm+Fz+le7fyc05NRliQLbiO1SzYeBbiQB5or4OUaPDKj2/rfbJBhCLHtjhkcPju1HnoOA9wR1XVrOW26PzJJKJzLb0FfJ/VsPbYVp36RbmiPEJu7r3lRw91Jbc7TKPjaNvMlV7Ml6e5Hg1Egp7a84kEtrm53ZKnYIv0QK2k=
